version: '3.8'

services:
  test:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
